node:                         # Config is hierarchical
  loompa: null # Simple value
  zippity: 1/10     # Value interpolation
  do: "oompa ${node.loompa}"  # String interpolation
  waldo: ???                  # Missing value, must be populated prior to access
